# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/node:10.13

    working_directory: ~/inveo-gatsby

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Gatsby Build
          command: ./node_modules/.bin/gatsby build

      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys
      - attach_workspace:
          at: public
      # - run:
      #     name: check project files
      #     command: |
      #       #  ls -la ~/.ssh/ && cat ~/.ssh/config && cat /home/circleci/.ssh/id_rsa_d675b5f987835b0ac2d588e7d845bb06 && cat config
      #       cd ~/project/public && ls -la

      - run:
          name: Deploy Over SSH
          command: |
            scp -P $SSH_PORT -r ~/project/public/public/* $SSH_USER@$SSH_HOST:$SSH_PATH
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
